image: thomaschln/r-devtools

# gitlab-ci file copied from https://www.r-bloggers.com/developing-r-packages-with-usethis-and-gitlab-ci-part-iii/

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

cache:
  paths:
  - $R_LIBS_USER

before_script:
  - echo '.libPaths("'${R_LIBS_USER}'")' > .Rprofile
  - apt-get update
  - apt-get install -y qpdf pandoc

stages:
  - deps
  - check
  - deploy

deps:
  stage: deps
  script:
  - R -e 'print(Sys.getenv("R_LIBS_USER"))'
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
  - R -e 'remotes::install_cran("liquidSVM", repos="http://pnp.mathematik.uni-stuttgart.de/isa/steinwart/software/R", build_opts="--no-multiarch", lib=Sys.getenv("R_LIBS_USER"))'
  - R -e 'lib=Sys.getenv("R_LIBS_USER"); print(lib); remotes::install_deps(lib=lib)'

check:
  stage: check
  script:
  - R -e 'devtools::check(check_dir = Sys.getenv("CHECK_DIR"), error_on = "warning")'
  - R -e 'devtools::install()'

pages:
  stage: deploy
  script:
  - R -e 'remotes::install_github("r-lib/pkgdown", lib=Sys.getenv("R_LIBS_USER"))'
  - R -e 'devtools::document()'
  - R -e 'pkgdown::build_site()'
  # - grep gitlab docs/reference/PRO4SAIL.html
  - mv docs public
  artifacts:
    paths:
    - public

  only:
  - master

